### ISSUE TITLE
Let's talk about, goals, features and porting quirks

### ISSUE THREAD

**Issue by fox1t** [fastify/fastify-passport#1]
Hi, I am in the process of porting passport to Fastify. The goal of this project is to have 100% compatibility with all the passport strategies already developed. 
I just finished porting the code 1:1 to TypeScript and now I am going to rewrite some parts that are not suitable anymore: 
1. original project doesn't use strict mode
2. almost all types are wrong
3. some parts could be optimized and speed up

There are some part of the code that need to be approached carefully and I'll use this thread to talk about them. First of all, there are two folders that need our attention, [framework](https://github.com/fox1t/passport/tree/master/src/framework) and [middleware](https://github.com/fox1t/passport/tree/master/src/middleware). These folders contains all the implementation that is bound to connect middleware, used by passport. As we can see on [`this.framework(connect())`](https://github.com/fox1t/passport/blob/master/src/authenticator.ts#L23), in the `authenticator` module, this, so called "framework", is pluggable using [framework() method](https://github.com/fox1t/passport/blob/master/src/authenticator.ts#L101). All the Fastify's specific implementation must be done inside a "compatible framework". 
Unfortunately there are some issues.
1. Let's start with `req.flash`. Passport uses flash messages to notify success or failure during authentication process (line [173](https://github.com/fox1t/passport/blob/master/src/middleware/authenticate.ts#L173) and [281](https://github.com/fox1t/passport/blob/master/src/middleware/authenticate.ts#L281)). Are we gonna support this?
2. Passport's `connect framework` [monkey patch http.IncomingMessage](https://github.com/fox1t/passport/blob/master/src/framework/connect.ts#L25) just to add some helpers methods, as `logIn` and `authenticate`. I really do not want to do that and, instead, I want to add it to Fastify's request object. However we need to be sure that all strategies will still work.
3. Speaking of that, `SessionStrategy`, the only included with passport, support [pausing IncomingMessage](https://github.com/fox1t/passport/blob/master/src/strategies/session.ts#L51), if `options.pauseStream` is passed. This works because req is a express.Request, that is extended from IncomingMessage. This is, of course, a problem for Fastify's request object.

**Comment by mcollina** [comment]
> Let's start with req.flash. Passport uses flash messages to notify success or failure during authentication process (line 173 and 281). Are we gonna support this?

Definitely. The "flash" is a concept born out of Ruby on Rails. I think the first step is to do a "fastify-flash" plugin that matches what passport needs. This is useful outside of passport. https://api.rubyonrails.org/classes/ActionDispatch/Flash.html.

I'll set up a repo for you: https://github.com/fastify/fastify-flash. Let me know if you need me to do anything. I've added Azure Pipelines. Once there is some code I'll add some config as well. 

> Passport's `connect framework` [monkey patch http.IncomingMessage](https://github.com/fox1t/passport/blob/master/src/framework/connect.ts#L25) just to add some helpers methods, as `logIn` and `authenticate`. I really do not want to do that and, instead, I want to add it to Fastify's request object. However we need to be sure that all strategies will still work.

We shouldn't do this. If Original passport strategies do not work, we change name of this module, and we add some more ;). This is a fork anyway.

> Speaking of that, `SessionStrategy`, the only included with passport, support [pausing IncomingMessage](https://github.com/fox1t/passport/blob/master/src/strategies/session.ts#L51), if `options.pauseStream` is passed. This works because req is a express.Request, that is extended from IncomingMessage. This is, of course, a problem for Fastify's request object.

I would not worry about this. That is an artifact of using middlewares, and it should not be an issue with fastify. Let's skip this feature.

I'd like to add one goal: *move from the middleware approach to Fastify lifecycle [hooks](https://www.fastify.io/docs/latest/Hooks/)*. This would make it natural to use fastify decorators as well, so it should be one of the first things to fix.

**Comment by fox1t** [comment]
Nice idea. I am going to work on fastify-flash then.
I absolutely agree on  "move from the middleware approach to Fastify lifecycle hooks": this is the frist and most important goal from the very beginning, otherwise we could just `fastify.use(passport)` XD

**Comment by fox1t** [comment]
Now that we have [fastify-flash](https://github.com/fastify/fastify-flash), I think that we can move on with our discussion. 😀

**Comment by mcollina** [comment]
What's the next step?

**Comment by fox1t** [comment]
I really want to support as many passport's plugins as possible. I think I'll explore passport internals to find the best way to port it to fastify's hooks.

**Comment by DragosRocsoreanu** [comment]
Is there any news on this implementation ?

**Comment by fox1t** [comment]
Hi, I was really busy in the past month. I will return on this as soon as possibile. We all need this, definitely. Do you want to help?

**Comment by gurpreetsingh2410** [comment]
Hi, Let me know if you need any help. Thanks

**Comment by Kolkies** [comment]
Any updates on this?

**Comment by ivorpad** [comment]
@fox1t Let me know if you need help. I would love to have PassportJS support in Fastify.

**Comment by fox1t** [comment]
Hi @ivorpad, thanks for reaching out! 
You can find the work done till now on this PR: https://github.com/fastify/fastify-passport/pull/3
As you can see @SerayaEryn handled it. I am here to answer any questions you have or to review your code, if needed.

**Comment by Eomm** [comment]
@ivorpad if you would like to send a PR to @SerayaEryn in order to complete the docs and test, I think it would speed up the process 👍

If @SerayaEryn agrees aswell

**Comment by SerayaEryn** [comment]
@ivorpad Help would be welcome. I think we can merge the PR #3 to the master if that helps.

**Comment by mcollina** [comment]
Released v0.1.0 with an initial implementation, thanks everybody!
