### ISSUE TITLE
All routes throw an "Invalid CORS origin option" error if used together with @fastify/cors and an async function as origin option

### ISSUE THREAD

**Issue by Charioteer** [fastify/fastify-passport#1181]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Plugin version

2.5.0

### Node.js version

20.12.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.5

### Description

Hi!

I don't know whether this bug should be rather reported in the [@fastify-cors](https://github.com/fastify/fastify-cors) repository. However, without using @fastify-passport, everything works fine on their side.

I have the following setup with @fastify-cors v9.0.1 (simplified for brevity):
```ts
import Fastify from "fastify"
import fastifyCors from "@fastify/cors"
import fastifyPassport from "@fastify/passport"
import fastifySecureSession from "@fastify/secure-session"
import fs from "node:fs"
import path from "node:path"

const asyncTask = () =>
  new Promise<void>((resolve) =>
    setTimeout(() => {
      resolve()
    }, 500)
  )

const fastify = Fastify()

fastify.register(fastifyCors, {
  origin: async function (origin, cb) {
    await asyncTask()
    cb(null, true)
  },
  credentials: true,
})

fastify.register(fastifySecureSession, {
  key: fs.readFileSync(path.resolve("keys", "secret-key")),
})
fastify.register(fastifyPassport.initialize())
fastify.register(fastifyPassport.secureSession())

fastify.get("/", (req, reply) => {
  reply.send({ hello: "world" })
})

await fastify.listen({ port: 3000 })

```

Now, when visiting the `/` route (or any other registered routes, if any), fastify throws an HTTP 500 error with the message "Invalid CORS origin option". This message is produced by @fastify-cors (see e.g. [here](https://github.com/fastify/fastify-cors/blob/master/index.js#L110) or [here](https://github.com/fastify/fastify-cors/blob/master/index.js#L120)). However, without calling `fastify.register(fastifyPassport.secureSession())` everything works just fine. It is very important to note that this issue only happens if the `origin` option of @fastify-cors is configured with an **async** function like I did. By simply removing the `async` keyword and the awaited `asyncTask()` statement, everything works again, even after calling `fastify.register(fastifyPassport.secureSession())`.

In conclusion, @fastify-passport works if @fastify-cors is configured like that:
```ts
fastify.register(fastifyCors, {
  origin: function (origin, cb) {
    cb(null, true)
  },
  credentials: true,
})
```

but not if configured like that:
```ts
fastify.register(fastifyCors, {
  origin: async function (origin, cb) {
    await asyncTask()
    cb(null, true)
  },
  credentials: true,
})
```

Again, I am not sure whether this is rather a problem of @fastify-cors or of @fastify-passport. Either way, I appreciate any comment on this issue. Thanks for your work and let me know if you need more information or help to fix this issue.

### Link to code that reproduces the bug

https://github.com/Charioteer/fastify-passport-invalid-cors-option

### Expected Behavior

I expected @fastify-passport to work with @fastify-cors even with an async function as the `origin` option of @fastify-cors without throwing an HTTP 500 error.

**Comment by climba03003** [comment]
Please don't mix the `async-await` with `callback`.
If you want to use `async-await`, just return the result.

```js
fastify.register(fastifyCors, {
  origin: async function (origin) {
    await asyncTask()
    return true
  },
  credentials: true,
})
```

or use thenable.


```js
fastify.register(fastifyCors, {
  origin: function (origin, cb) {
    asyncTask().then(() => cb(null, true))
  },
  credentials: true,
})
```

**Comment by Charioteer** [comment]
@climba03003 Hi and thanks for reaching back to me. I don't know what I was thinking that I didn't realize it in this case. I am used to the "either callback or async" semantics of fastify but this time I probably got confused a little by the fastify-cors documentation and the fact that my initial code still worked as long as fastify-passport was not involved. Sorry for bothering. I am closing this issue of course!
