### ISSUE TITLE
Request user is null when reading from within Mercurius

### ISSUE THREAD

**Issue by sorodrigo** [fastify/fastify-passport#320]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.20.2

### Plugin version

0.4.3

### Node.js version

14.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

I've been trying to integrate Mercurius with my Rest API backend. I have it working without auth, and I really would like to be able to read the `request.user` field from the Mercurius context. I don't understand why the value is always null.

```ts
instance.register(passportSetup);
instance.register(
  Mercurius,
  {
    schema,
    graphiql: true,
    async context(request) {
      return {
        user: request.user, // always null
        origin: getRequestOrigin(request)
      };
    }
  }
);
```

```ts
export const passportSetup = fp(async (instance) => {
  instance.register(fastifySecureSession, {
    key: Buffer.from(COOKIE_SECRET, 'hex'),
    cookieName: 'session',
    cookie: {
      maxAge: 24 * 60 * 60 * 1000 * 30,
      // Do not change the lines below, they make cy.auth() work in e2e tests
      secure: process.env.NODE_ENV !== 'development' && !process.env.INSECURE_AUTH,
      signed: process.env.NODE_ENV !== 'development' && !process.env.INSECURE_AUTH,
    },
  });
  instance.register(passport.initialize());
  instance.register(passport.secureSession());

  passport.registerUserSerializer(async (passportUser: { email: string, redirect: string }) => {
    const { email, redirect } = passportUser;
    await instance
      .db('users')
      .insert({
        email,
        confirmed_at: new Date(),
      })
      .onConflict('email')
      .ignore();

    const [user] = await instance
      .db<{ id: string, email: string }>('users')
      .where('email', email)
      .select('id');

    return { userId: user.id, redirect };
  });

  passport.registerUserDeserializer(async ({ userId, redirect }: { userId: string, redirect: string }) => {
    const [user] = await instance.db('users').where('id', userId);
    return { ...user, redirect };
  });

  passport.use(STRATEGY, magicLink);
});
```

### Steps to Reproduce

Create a custom context and try to access the `passportUser` from within the request or the `reply.request` objects.

### Expected Behavior

It should be possible to access the session user after deserialization by passport.

**Comment by mcollina** [comment]
Could you please upload a runnable example that shows this behavior?

**Comment by sorodrigo** [comment]
ok I will prepare something do you want a github repo or something else like code-sandbox?

**Comment by mcollina** [comment]
github repo is better

**Comment by sorodrigo** [comment]
OK I added you as a collaborator https://github.com/magic-embed/core/blob/master/packages/api/src/setup.ts#L53

**Comment by mcollina** [comment]
I'm sorry but I am not reviewing private code.

**Comment by sorodrigo** [comment]
Ok thanks and sorry for that. I'll move it to a public repo this afternoon.

**Comment by sorodrigo** [comment]
Here's the repro code. https://github.com/sorodrigo/repro-fastify

Again I'm sorry for sending the private repo (is not a work thing it's a pet project) but I thought the real case scenario was maybe more helpful. Hope I wasn't part of the motivation behind [this tweet](https://twitter.com/matteocollina/status/1437455583909748742). I appreciate the help and effort you're putting!

**Comment by simoneb** [comment]
@sorodrigo did you have a chance to take another look at this? If not, I'm going to suggest to close it as stale.

**Comment by sorodrigo** [comment]
Apologies, I've been slammed at work. Will comment with repro once I can dedicate some time. Thanks!!

**Comment by yorch** [comment]
@sorodrigo seems like your problem is that you haven't add a `preValidation` to your Mercurius plugin (which I'm not sure how to do), so after the login flow is complete and the `session` cookie is there, subsequent requests can still go through the `fastify-passport` flow and get the `user` object populated.

I'm in the process of implementing a similar application with Apollo Server and trying to figure out how to add that `preValidation` to Apollo.
