### ISSUE TITLE
Socket IO middleware Support

### ISSUE THREAD

**Issue by PhilipWee** [fastify/fastify-passport#385]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Right now fastifyPassport registers as a fastify plugin, but it is incompatible with Socket IO middleware

I don't mind helping to implement this feature

### Motivation

I don't want to have to register the passport strategies twice for socket IO and fastify passport

### Example

Assuming you are using fastify socket io:
`
server.register(fastifySecureSession, { key: fs.readFileSync(path.join(__dirname, 'secret-key')) })
// initialize fastify-passport and connect it to the secure-session storage. Note: both of these plugins are mandatory.
server.register(fastifyPassport.initialize())
server.register(fastifyPassport.secureSession())

server.io.use(fastifyPassport.io.initialize())
server.io.use(fastifyPassport.io.secureSession())
`

**Comment by airhorns** [comment]
Is there anything wrong with registering the strategies twice other than it just being a little annoying? I feel like it would be a bit weird for this library to couple directly to `fastify-socket.io`, it would be really hard for us to maintain integrations with the many plugins in the fastify ecosystem. Also, for what it's worth, `fastify-passport` works fine with `fastify-websocket` as `fastify-websocket` runs hooks for websocket upgrade requests, so this may be a thing that `fastify-socket.io` needs to fix on their end as well.

**Comment by PhilipWee** [comment]
So maybe its a case of fastify-socket.io should use fastify routes for upgrading the initial connextion then

**Comment by airhorns** [comment]
That definitely would make things easier! We added support for `reply.hijack()` to fastify a while ago to support exactly this -- the request can be a normal request dispatched through the normal fastify hook cycle until one hook decides to take over and do something with it, which `fastify-websocket` does. I am not certain but I think `fastify-socket.io` should be able to do the same!
