### ISSUE TITLE
Local Strategy bad request

### ISSUE THREAD

**Issue by gasner** [fastify/fastify-passport#401]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3

### Plugin version

0.4.3

### Node.js version

14

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20

### Description

Hi, I trying to use LocalStrategy.
I succeeded to do login but the other request return a Bad Request.

### Steps to Reproduce

    

```
module.exports = fp(async function (fastify, opts) {
    fastify.register(fastifySecureSession, {
        key: fs.readFileSync(path.join(__dirname, '../secret-key')),
    })
    fastify.register(fastifyPassport.initialize())
    fastify.register(fastifyPassport.secureSession())

    fastifyPassport.use("local", new LocalStrategy(
        function (username, password, done) {
            User.findOne({email: username}, function (err, user) {
                if (err) {
                    return done(err);
                }
                if (!user) {
                    return done(null, false);
                }
                if (!user.comparePassword(password)) {
                    return done(null, false);
                }
                return done(null, user);
            });
        }
    ));
    // register a serializer that stores the user object's id in the session ...
    fastifyPassport.registerUserSerializer(async (user, request) => user.id);

    // ... and then a deserializer that will fetch that user from the database when a request with an id in the session arrives
    fastifyPassport.registerUserDeserializer(async (id, request,) =>{
        return await User.findById(id);
    });

})
```
and this is my route

```
  // always return Bad Request
    fastify.get('/auth', {preValidation:  fastifyPassport.authenticate('local',{ successFlash: 'Welcome!' })},
        async (req) => {
            return {
                "title": 'hello world!',
                user: req.user

            }
        }
    )
    
    //work good!
    fastify.post(
        '/login',
        {
            preValidation: fastifyPassport.authenticate('local', {
                successRedirect: "/",
                failureRedirect: "/login",
                failureFlash: true,
            })
        },
        () => {
            return {hello: "world"}
        }
    )

```

### Expected Behavior

Expected to get the user and not Bad Request

**Comment by mcollina** [comment]
Please provide a reproducible example.

**Comment by gasner** [comment]
```JS
const fastify = require("fastify");
const fastifyPassport = require("fastify-passport");
const fastifySecureSession = require("fastify-secure-session");
const LocalStrategy = require("passport-local");
const mongoose = require("mongoose");
const path = require("path");
const fs = require("fs");

mongoose.connect("mongodb://127.0.0.1:27017/", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    dbName: "test",
});
const Schema = mongoose.Schema;
const userSchema = new Schema(
    {
        username: {
            type: String,
            required: true,
            unique: true,
        },
        password: { type: String, required: true },
    },
    { timestamps: true }
);
const User = mongoose.model("user", userSchema);

const server = fastify();
server.register(fastifySecureSession, {
    key: fs.readFileSync(path.join(__dirname, "secret-key")),
});

server.register(fastifyPassport.initialize());
server.register(fastifyPassport.secureSession());

fastifyPassport.use(
    "local",
    new LocalStrategy(function (username, password, done) {
        User.findOne({ username: username }, function (err, user) {
            if (err) {
                return done(err);
            }
            if (!user) {
                return done(null, false, { message: "Incorrect username." });
            }
            return done(null, user);
        });
    })
);

fastifyPassport.registerUserSerializer(async (user, request) => {
    return user.id;
});

fastifyPassport.registerUserDeserializer(async (id, request) => {
    let user = await User.findById(id);
    return user;
});

server.post("/register", async (req, reply) => {
    await User.create({
        username: req.body.username,
        password: req.body.password,
    });
    return { a: "hey" };
});

server.post(
    "/login",
    {
        preValidation: fastifyPassport.authenticate("local", {
            successRedirect: "/auth",
            authInfo: false,
        }),
    },
    () => {}
);

server.get(
    "/auth",
    {
        preValidation: fastifyPassport.authenticate("local", {
            authInfo: true,
        }),
    },
    async (req, res) => {
        console.log(req, res);
        return "Hey";
    }
);

server.listen(3000);

```

Thanks!

**Comment by CarleneCannon-Conner** [comment]
Assigning to myself @CarleneCannon-Conner

**Comment by mcollina** [comment]
go for it!

**Comment by CarleneCannon-Conner** [comment]
Hi @gasner I have been having a look into this issue.  Am I right in understanding that you want to call `passport.authenticate('local', ...` on  a GET request to obtain user data? 

I was able to reproduce the Bad Request as per your example. I found that the error only occurs on GET requests where a `fastifyPassport.authenticate()` is called passing in `passport-local` as a strategy. I then had a look at the this repository to see if any tests were failing, in particular the GET requests and they all appeared to be working, however they used different strategies. This lead me to looking into the strategy used in your example which lives in the passport-local repository. The [readme](https://github.com/jaredhanson/passport-local) shows this POST example 

```
app.post('/login', 
  passport.authenticate('local', { failureRedirect: '/login' }),
  function(req, res) {
    res.redirect('/');
  });
  ```
  
  And there are no GET examples. 
  
 The readme goes on to point out an [example](https://github.com/passport/express-4.x-local-example/blob/8b45c5a0fe077f16a310e9443e56535e67ac8051/README.md) using express. Looking at this code, again I see no examples of GET requests where authenticate is called on passport. The example shows that the [GET /login](https://github.com/passport/express-4.x-local-example/blob/master/views/login.ejs) renders a page that allows the user to enter in credentials in a form and by submitting that form the [POST /login/password](https://github.com/passport/express-4.x-local-example/blob/master/routes/auth.js) request gets called. It's there that authenticate gets called on passport.
  
  ```
router.post('/login/password', passport.authenticate('local', {
  successRedirect: '/',
  failureRedirect: '/login',
  failureMessage: true
}));
  ```
  
From what I have found, it does not look like you can obtain user data by calling `passport.authenticate`, passing in `passport-local` as a strategy in a GET request. Perhaps another strategy would be more useful.

**Comment by Pazaz** [comment]
Ran into this issue myself... it seems that `passport.authenticate(...)` is used to validate a username/password primarily, and the result gets stored in req.user. Not sure what authInfo does but I get the same bad request error, so I don't think you should call it regularly, unless this is an oversight/break down somewhere. You'll also see req.isAuthenticated() should return true regardless of a pre-validation hook being added now.

In your normal GET requests you should use req.user, and you can add your own preValidation function to check/redirect.

i.e. (do not take this as best practice)
```js
async function redirectToLogin(req, res) {
    if (req.isUnauthenticated()) {
        res.redirect(302, '/login'); // or return an error. I use this to redirect to a page to log in with
    }
}

fastify.get('/',
    { preValidation: async (req, res) => await redirectToLogin(req, res) },
    (req, res) => {
        return {
            index: true
        };
    }
)

fastify.post('/login',
    { preValidation: Passport.authenticate('local', { successRedirect: '/', failureRedirect: '/login' }) },
    () => { }
);
```

**Comment by CarleneCannon-Conner** [comment]
Thank you @Pazaz for the additional information. The 'Bad Request' is likely coming form the `Strategy.prototype.authenticate` function [here](https://github.com/jaredhanson/passport-local/blob/master/lib/strategy.js). It expects both a username and a password to be provided via the body or query in the request. 

@gasner I hope our input was helpful.

I would like to close this issue.

**Comment by simoneb** [comment]
Closing
