### ISSUE TITLE
passport-github verify callback never called?

### ISSUE THREAD

**Issue by julie-ng** [fastify/fastify-passport#473]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Use Case

- An app that will make calls to the GitHub API on behalf of user (e.g. git commits, gists, etc.)
- I want to use the GitHub strategy, both for AutheNtication (who is user?) and AuthoriZation (which repos belonging to user does app have access to?).

### Problem

- AuthN layer works as in a user is redirected to login if they are not logged in.
- But I cannot figure out how to get the access token or user profile

### Example Code

Here is a reduced code sample. In my testing, the `console.log(profile)` is **_never_** called in Fastify. The same setup and code works in Express.

The `/protected` route will redirect to GitHub, which will redirect to the `/auth/github/callback` route, but the verify callback is never called :-(

### Getting Access Tokens

Per [GitHub Docs](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#2-users-are-redirected-back-to-your-site-by-github) I can take the code from the callback URL, e.g. `http://127.0.0.1:3000/auth/github/callback?code=12fxxxxxx` to fetch the access and refresh tokens. But I don't want to if passport can do it for me.

I did rush this this morning. So maybe I am doing it wrong?

```javascript
const PORT = process.env.port || 3000

const fastify = require('fastify')({ logger: true })
const fastifyPassport = require('fastify-passport')
const fastifySecureSession = require('fastify-secure-session')

const GitHubStrategy = require('passport-github').Strategy
const strategyOpts = {
  clientID: process.env.GITHUB_CLIENT_ID,
  clientSecret: process.env.GITHUB_CLIENT_SECRET,
  callbackURL: 'http://127.0.0.1:3000/auth/github/callback'
}

const notForProductionKey = 'no-encryption-key-for-local-dev-min-32-bytes'
fastify.register(fastifySecureSession, { key: notForProductionKey })
fastify.register(fastifyPassport.initialize())
fastify.register(fastifyPassport.secureSession())

fastifyPassport.use('github', new GitHubStrategy(strategyOpts, function (accessToken, refreshToken, profile, cb) {
  console.log('**** Is this ever called??? *******') // <-- NEVER called in Fastify ⁉️
  console.log(profile) // <-- for testing only
  return cb(null, profile)
}
))


/**
 * Routes
 */

fastify.get('/', function (request, reply) {
  reply.send({
    hello: 'world',
    protected: false
  })
})

fastify.get('/protected', { preValidation: fastifyPassport.authenticate('github', { authInfo: false }) }, async (request, reply, err, user, info, status) => {
  if (err !== null) {
    console.warn(err)
  } else if (user) {
    console.log(`Hello ${user.name}!`)
    reply.send(user)
  }

  reply.send({
    hello: 'protected',
    protected: true
  })
})

fastify.get('/auth/github/callback', (req, reply) => {
  // reply.redirect('/')
  reply.send('called back')
})


/**
 * Run the Server
 */
fastify.listen(PORT, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
})
```

**Comment by airhorns** [comment]
Offhand I am not sure why exactly this is happening, but, in my project we're using `passport-github2` which is a maintained fork of `passport-github`, and it seems to work ok with `fastify-passport`! Want to try that one out?

**Comment by darkgl0w** [comment]
Hello.

can you try with this piece of code :

```js
const PORT = process.env.port || 3000

const fastify = require('fastify')({ logger: true })
const fastifyPassport = require('fastify-passport')
const fastifySecureSession = require('fastify-secure-session')

const { Strategy: GitHubStrategy } = require('passport-github')
const strategyOpts = {
  clientID: process.env.GITHUB_CLIENT_ID,
  clientSecret: process.env.GITHUB_CLIENT_SECRET,
  callbackURL: 'http://127.0.0.1:3000/auth/github/callback'
}

const notForProductionKey = 'no-encryption-key-for-local-dev-min-32-bytes'
fastify.register(fastifySecureSession, { key: notForProductionKey })
fastify.register(fastifyPassport.initialize())
fastify.register(fastifyPassport.secureSession())

fastifyPassport.use('github', new GitHubStrategy(strategyOpts, function (accessToken, refreshToken, profile, cb) {
  console.log('**** Is this ever called??? *******') // <-- NEVER called in Fastify ⁉️
  console.log(profile) // <-- for testing only
  return cb(null, profile)
}
))


/**
 * Routes
 */

fastify.get('/', function (request, reply) {
  reply.send({
    hello: 'world',
    protected: false
  })
})

fastify.get('/protected', { onRequest: fastifyPassport.authenticate('github', { authInfo: false })}, (request, reply) => {
  reply.send({
    hello: 'protected',
    protected: true
  })
})

fastify.get('/auth/github/callback', { onRequest: fastifyPassport.authenticate('github', { authInfo: false })}, (request, reply) => {
  // reply.redirect('/')
  reply.send('called back')
})


/**
 * Run the Server
 */
fastify.listen(PORT, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
})
```

It seems that the github auth callback url must call `fastifyPassport.authenticate()` method too.

**Comment by julie-ng** [comment]
Thanks @darkgl0w! That seems to work. Is there a reason why the callback needs it too? Is there something I missed in the documentation?

**Comment by darkgl0w** [comment]
No you didn't miss anything. It is the plugin documentation that needs some love. I have spotted some issues that are worth a PR when looking at this issue. 😝

In this particular case the plugin code itself is well commented. 😸

**Comment by darkgl0w** [comment]
@airhorns yes it is the case for express as well. I will submit a PR to add a note about this.

**Comment by julie-ng** [comment]
> No you didn't miss anything. It is the plugin documentation that needs some love. I have spotted some issues that are worth a PR when looking at this issue. 😝
> 
> In this particular case the plugin code itself is well commented. 😸

Yeah, documentation can really use from love. I find it detailed - but not in a good way that's easy to sort out, esp. since

- `{ authInfo@ false }` is never explained
- And lines like this are just 😵‍💫 - so many params… and if I wanted to skip `authInfo`, could I? Or do I need an empty object? 🤔
  ```javascript
  fastify.get(
    '/',
    { preValidation: fastifyPassport.authenticate('test', { authInfo: false }) },
    async (request, reply, err, user, info, status) => {
  ```

I'll try to figure out some of this, but it's a struggle right now.

If it's well documented in the code, you should consider using JSDoc to publish a docs site. And I'll shamelessly plug my own template here ;-) https://www.npmjs.com/package/tidy-jsdoc

Closing issue for now since original problem described is now solved.
