### ISSUE TITLE
Using fastify-secure-session with openid-client strategy

### ISSUE THREAD

**Issue by jonaskello** [fastify/fastify-passport#491]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm trying to use `fastify-secure-session` with [openid-client](https://github.com/panva/node-openid-client) passport strategy.

It redirects correctly to the OIDC provider and redirects back correctly but then I get this error:

```
did not find expected authorization request details in session, req.session[\"oidc:xxxx\"] is undefined
```

I've looked into the source code for possible causes of this and I found something that I think may be the cause. Looking at how `fastify-secure-session` requires you to set session values using the `request.session.set(key, value)` method like this (example from the [readme](https://github.com/fastify/fastify-secure-session/blob/master/README.md)):

```ts
  request.session.set('data', request.body)
})
```

And then looking into the source code for `openid-client` which expects to be able to do `req.session[key] = value` as for example in [this line](https://github.com/panva/node-openid-client/blob/main/lib/passport_strategy.js#L95):

```ts
 req.session[sessionKey] = pick(params, 'nonce', 'state', 'max_age', 'response_type');
```

I think this cannot really be compatible? On the one side `req.session.set(key, value)` is required, and on the other side `req.session[key] = value` is used. Or is there some adaptation going on inside of `fastify-passport` to make this compatible?

**Comment by mcollina** [comment]
I think `req.session.set(key, value)` is a fundamentally safer API than `req.session[key]`.

Anyway, I have opened https://github.com/fastify/fastify-secure-session/issues/113 if you would like to take a stab at both.

**Comment by xkal36** [comment]
This functionality is added here: https://github.com/fastify/fastify-secure-session/pull/121

**Comment by simoneb** [comment]
@xkal36 do we need to do any changes in this package to get the new feature in that PR?

**Comment by xkal36** [comment]
> @xkal36 do we need to do any changes in this package to get the new feature in that PR?

Not here - when we update the minor version of `fastify-secure-session`, it will be picked up here: https://github.com/fastify/fastify-passport/blob/main/package.json#L51

**Comment by climba03003** [comment]
> do we need to do any changes in this package to get the new feature in that PR?

No changes needed, but a test for it are welcome.

**Comment by simoneb** [comment]
@xkal36 can you take this? ^

**Comment by xkal36** [comment]
@jonaskello would you mind adding a reproducible example please? I am trying to add an integration test and I need to see how you create the client and issuer for example.
