### ISSUE TITLE
Broken CI

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-passport#5]
It seems CI is broken: https://github.com/fastify/fastify-passport/runs/1112429485.

I think we should skip the `dist/` folder in eslint:

```
> fastify-passport@0.0.1 lint /home/runner/work/fastify-passport/fastify-passport
> eslint '*/**/*.{js,ts,tsx}'


/home/runner/work/fastify-passport/fastify-passport/dist/AuthenticationRoute.d.ts
```

**Comment by mcollina** [comment]
@airhorns can you take a look?

**Comment by fox1t** [comment]
Skipping that folder should fix this issue.
