### ISSUE TITLE
[TypeScript] Unable to override type of request.user 

### ISSUE THREAD

**Issue by mgcrea** [fastify/fastify-passport#51]
## 🐛 Bug Report

Not sure if this is an actual bug or a typescript misconfiguration on my side but I haven't found a way to properly override the type of the `request.user`, and it is not explained in the docs:

## To Reproduce

```ts
import { User } from 'src/typings';

declare module 'fastify' {
  interface FastifyRequest {
    user: User;
  }
}
```

Triggers an error:

```
Subsequent property declarations must have the same type.  Property 'user' must be of type 'unknown', but here has type 'User'.ts(2717)
```

## Expected behavior

Working override

## Your Environment

- *node version*: 14
- *fastify-passport version*: ^0.1.0
- *os*: Mac
- *TypeScript*: 4.1.2

**Comment by airhorns** [comment]
As the types are right now there is no way to do declaration merging from your own types, you're right. We should change that. I think until https://github.com/microsoft/TypeScript/issues/31894 ships the only way to do it would be to export a type that you declaration merge with like so:

```typescript
import { User as AppUser } from 'src/typings';

declare module 'fastify-passport' {
  interface User {
    [key in keyof AppUser]: AppUser[key]
  }
}
```

or something like that. I am not certain that would work but that would solve your problem, right? Also, @fox1t seems extra knowledgeable about TypeScript stuff like this, maybe he has seen other fastify modules solve this problem in a simpler way.
