### ISSUE TITLE
Flash plugin requires a valid session error

### ISSUE THREAD

**Issue by bragovo** [fastify/fastify-passport#52]
I'm trying to use this plugin with NestJS. My session works fine.
```
// main.ts
await app.register(fastifySecureSession, {...})

// auth.controller.ts
login(@Req() req): any {
  console.log(!!req.session) // print true
  return true
}
```

But after adding passport I get error "Flash plugin requires a valid session." https://github.com/fastify/fastify-flash/blob/master/src/index.ts#L12
```
await app.register(fastifySecureSession, {...})
await app.register(fastifyPassport.initialize())
await app.register(fastifyPassport.secureSession())
```

How I can fix it?

The second question: is it possible to make `fastify-flash` optional? In my project I don't need any flash.

**Comment by airhorns** [comment]
I am not super familiar with NestJS, but could it be that the session plugin is registered in a different fastify plugin encapsulation context than fastify-passport? 

It is possible to make `fastify-flash` optional, no one has done it yet though. Happy to accept a PR! I think it should be required by default in order to maintain as-close-to-passport-as-possible functionality, but disabling it would be fine.

**Comment by airhorns** [comment]
@bragovo did you ever figure out which side of this setup was causing your issue?

**Comment by bragovo** [comment]
@airhorns unfortunately not, in my case I don't need passport at all :-D
So, I think this issue can be closed.

**Comment by torte** [comment]
I know this is closed, but I just ran into the same issue. The problem is that my server does not need the flash plugin (and also not session plugin), so this is quite cumbersome. I can't seem to turn this off as well via passport configuration.

**Comment by airhorns** [comment]
Yeah, I agree! Want to send a PR? The original `passport` library hardcodes a dependency on a flash system but I think we can do better.

**Comment by torte** [comment]
@airhorns Yeah, I will have a look at it later. 
I can't really see it as a dependency in original passport library, at least not that it is a requirement. Should be the same here I think (same for sessions).

**Comment by mcollina** [comment]
PRs are welcomed!
