### ISSUE TITLE
Failed to serialize user into session

### ISSUE THREAD

**Issue by SKrind0** [fastify/fastify-passport#522]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.28.0

### Plugin version

0.5.0

### Node.js version

17.8.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

21H2

### Description

when i use registerUserSerializer and registerUserDeserializer i get this error
![image](https://user-images.githubusercontent.com/68449193/163594498-a3706a95-ba70-4a6e-8df3-9b2c02bc60de.png)

### Steps to Reproduce

code:
![code](https://user-images.githubusercontent.com/68449193/163594703-b116be71-1aa4-4cf9-b2d9-f3806a7c5d81.png)

### Expected Behavior

I need help please

**Comment by SKrind0** [comment]
I already resolved it

**Comment by airhorns** [comment]
What was the issue? Should we add some docs/

**Comment by SKrind0** [comment]
> What was the issue? Should we add some docs?

It was my mistake when using discord-passport without reading the documentation completely 😅 but I already solved it
