### ISSUE TITLE
Calling Strategy.fail with 2 arguments is misinterpreted by the compiler

### ISSUE THREAD

**Issue by mmahkamov** [fastify/fastify-passport#627]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.1

### Plugin version

2.1.0

### Node.js version

16.4.2

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Here's the declaration of the fail() method in the base Strategy class: https://github.com/fastify/fastify-passport/blob/main/src/strategies/base.ts#L55

```
fail!: ((challenge?: any, status?: number) => void) | ((status?: number) => void)
```

When calling with 1 number argument, there's no problem:

```
this.fail(403);
```

But TypeScript is failing to find the variant with 2 arguments:
```
return this.fail({
  message: request.query['error_description'],
}, 400);
```

getting an error:
```
TS2554: Expected 0-1 arguments, but got 2
```

### Steps to Reproduce

1. Create a custom strategy subclassed from the Strategy class of @fastify/passport
2. Call this.fail(null, 401)

### Expected Behavior

The code should compile when calling Strategy.fail() with 2 arguments.

**Comment by airhorns** [comment]
Hm, that's strange! My guess is we're doing something wrong with the types where that fail signature you mentioned isn't the one being used within your subclass for some reason. Are you using a strategy subclass from `passport` and not `fastify-passport` perhaps?

**Comment by mmahkamov** [comment]
@airhorns I've double checked that I'm importing the base Strategy class from @fastify/passport:
```
import { Strategy } from '@fastify/passport';
```

I've also verified that `passport`'s `StrategyCreatedStatic` class has a fixed number of 2 arguments in its `fail()` method:
```
fail(challenge?: string | number, status?: number): void;
```

We were using `passport` before and it was compiling without errors. Now that we're trying to port the custom strategies to `@fastify/passport` we're facing the issue above.

I can try to set up a repo where the issue can be reproduced, if you wish.

**Comment by mmahkamov** [comment]
@airhorns This minimal code example can reproduce the issue:

```
class Base {
    authenticate() {};
    fail!: ((challenge?: any, status?: number) => void) | ((status?: number) => void);
}

class Derived extends Base {
    authenticate(): void {
        this.fail(null, 400);
    }
}

const instance = new Derived();
instance.authenticate();
```

**Comment by mmahkamov** [comment]
@airhorns Simplest repo to reproduce the issue: https://github.com/mmahkamov/fastify-passport-issue-627

Please let me know if I can provide any additional data.

**Comment by mmahkamov** [comment]
@airhorns Possible solution would be to align the declaration of `fail()` with its definition at https://github.com/fastify/fastify-passport/blob/main/src/AuthenticationRoute.ts#L189

```
fail!: (challengeOrStatus?: string | number | any, status?: number) => void;
```

**Comment by airhorns** [comment]
Hm, I think that maybe we need to use function overloading in our type signature for `.fail` instead of a union. Want to take a crack at a PR?

**Comment by mmahkamov** [comment]
@airhorns OK, will create a PR.

Here's the fix I came up with by using intersection instead of a union.

```
class Base {
    authenticate() {};
    fail!: ((challenge?: any, status?: number) => void) & ((status?: number) => void);
}

class Derived extends Base {
    authenticate(): void {
        this.fail('Authentication has failed!', 400);
        this.fail(400);
    }
}

const instance = new Derived();

instance.fail = function (challengeOrStatus?: string | number | undefined, status?: number) {
    console.log(`challengeOrStatus: ${challengeOrStatus}`);
    console.log(`status: ${status}`);
}

instance.authenticate();
```

Output:

```
challengeOrStatus: Authentication has failed!
status: 400
challengeOrStatus: 400
status: undefined
```

**Comment by mmahkamov** [comment]
@airhorns Submitted a PR for this issue.

I believe the `failureFlash` option is currently ignored, so passing a message to Strategy.fail() has no effect.

I'll create a separate bug for that.
