### ISSUE TITLE
Fastify Custom Strategy, redirect method not working - TypeError: res.setHeader is not a function

### ISSUE THREAD

**Issue by mjad218** [fastify/fastify-passport#686]
### Prerequisites

- [X] I have searched existing issues to ensure the bug has not already been reported

- [x] I have written a descriptive issue title

### Fastify version

4.6.3

### Node.js version

16

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11.3

### Description

Hi, 
I am trying to develop a custom strategy for Paypal. I am using fastify-passport@2.2.0. 

I am using Fastify with Nest.js. 

Here is my Strategy: 
```typescript
import { Strategy as FastifyStrategy } from '@fastify/passport';
import * as paypal from 'paypal-node-sdk';

class Strategy extends FastifyStrategy {
  private options;
  public name: string;
  private callback;
  constructor(options, callback) {
    super('paypal');
    this.options = options;
    this.name = 'paypal';
    this.callback = callback;
    paypal.configure({});
  }
  async authenticate(
    req,
    options?: any,
  ) {
    if (req.query && req.query['error']) {
      throw 'Query Error';
    }
    if (req.query && req.query['code']) {
      let code = req.query['code'];
      try {
        return this.getUserProfile(code);
      } catch (e) {
        return this.error(e);
      }
    }
    const location = await paypal.openIdConnect.authorizeUrl({
      scope: this.options.scope,
    });

    return this.redirect(location, 302);
   // the line above causes a problem 
  }

  verified(err, user, info) {
    if (err) {
      return this.error(err);
    }
    if (!user) {
      return this.fail(info);
    }
    this.success(user, info);
  }

  getUserProfile = async (code) => {
    // function to get the user data from Paypal;
  };
}

export default Strategy;
```

the redirect method seems to have a bug or something, it causes this error: 

```sh
res.setHeader('Location', url);
            ^
TypeError: res.setHeader is not a function
```

### Steps to Reproduce

Just try to implement a strategy and call the redirect method. 

### Expected Behavior

I expect the redirect method to work properly and redirect to the intended destination.

**Comment by mjad218** [comment]
I have solved this issue. 

Nest.js repo has an issue similar to this. [similar issue](https://github.com/nestjs/nest/issues/5702) 

in order to solve this. 
I added this code to my application. 

```
    instance.addHook('onRequest', (request, reply, done) => {
      reply.setHeader = function (key, value) {
        return this.raw.setHeader(key, value);
      };
      reply.end = function () {
        this.raw.end();
      };
      request.res = reply;
      done();
    });
```

**Comment by Eomm** [comment]
Not sure what is going on here because I don't see the code that is calling those methods, but that monkey patching smells a bit.
I wonder if `request.res = reply.raw` would be a litter nicer.

**Comment by mjad218** [comment]
This called by @nestjs/passport in a Nest.js project. 

This enables me to use [Guards](https://docs.nestjs.com/guards). 

Regarding the code calling the strategy, you can find it below. 
```
import { PassportStrategy } from '@nestjs/passport';
import { Injectable } from '@nestjs/common';
import { AuthService } from '../auth.service';
import Strategy from '../custom-strategies/Paypal';

@Injectable()
export class PaypalStrategy extends PassportStrategy(Strategy, 'paypal') {
  constructor(private authService: AuthService) {
    super({
      clientID: process.env.PAYPAL_CLIENT_ID,
      clientSecret: process.env.PAYPAL_CLIENT_SECRET,
      callbackURL: `http://127.0.0.1:8080/auth/paypal/redirect`,
      scope: 'openid email address profile',
    });
  }

  async validate(
    accessToken: string,
    refreshToken: string,
    profile: any,
    done,
  ) {
    const {
      user_id,
      email,
      verified,
      address: { country },
      email_verified,
      name,
    } = profile;    
      // user = await this.authService.signUp(newUser);
    }
    return done(null, newUser, null);
  }
}

```
In the code snippet above, I import the custom strategy that I added to the issue.
```
import Strategy from '../custom-strategies/Paypal';
```

Nest js then takes care of passing the `validate function` to that strategy besides the options object. 

You may read more about how Nestjs integrates with Passportjs 

Finally, I can use a guard before my routes to invoke the strategy.

```
  import { PaypalGuard } from './guard/PaypalGuard.guard';

  @UseGuards(PaypalGuard)
  @Get('paypal')
  async paypalAuth(@Response() res) {}

  @Get('/paypal/redirect/')
  @UseGuards(PaypalGuard)
  paypalAuthRedirect(@Res() res) {
    res.redirect(302, process.env.FRONT_END_URL);
  }

```

`PaypalGuard` is a custom guard for my PaypalStrategy. 

You can find more about that on [the Nest js docs](https://docs.nestjs.com/security/authentication).
