### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by airhorns** [fastify/fastify-passport#69]
@mcollina a few key fixes have landed on `main` that I'd like to release! I thought I might have had publish permissions to the `fastify-passport` npm package but I don't seem to. Would you mind adding me or releasing v0.2.0 (which has been tagged and pushed)? Thanks!

**Comment by mcollina** [comment]
what's your npm handle? You can also reach me on the Fastify discord server for these kind of things :)

**Comment by airhorns** [comment]
I'm @airhorns , and ok, thanks!!

**Comment by mcollina** [comment]
I've invited you to the org, let me know.
