### ISSUE TITLE
fastifyPassport.initialize is not a function

### ISSUE THREAD

**Issue by aspiiire** [fastify/fastify-passport#82]
As soon as fastifyPassport starts i get "fastifyPassport.initialize is not a function", if a debug fastifyPassport i have only default and strategy present

Steps to reproduce

```js
  app.register(fastifySecureSession, { key: "akey" });
  
  app.register(fastifyPassport.initialize());
  app.register(fastifyPassport.secureSession());
```

- *node version*: 15.0.1
- *fastify version*: >=3.8.0
- *os*: Linux

**Comment by mcollina** [comment]
Are you using typescript, faux modules (`esm` module or webpack) or native esm?

**Comment by aspiiire** [comment]
Javascript with webpack

**Comment by mcollina** [comment]
you are likely having some problems with `import` and that config. Try using require instead.

**Comment by aspiiire** [comment]
I cannot use require, also in the example it uses import, it should work...

**Comment by mcollina** [comment]
@fastify/typescript could you take a look at this? I think we should update the readme somehow to show how to use this module with commonjs instead, as `import` can mean so many different things to folks.

> there is any alternative? i am stuck and i need this package do you have any suggestion how to move forward?

I recommend you to check your webpack config and inspect how the final code is actually generated. You might just have to tweak some options to make it work.

**Comment by aspiiire** [comment]
Thanks you for your help Matteo and also thank for this amazing package

**Comment by mcollina** [comment]
I didn't write this :). @airhorns did most of the work!

**Comment by aspiiire** [comment]
> I didn't write this :). @airhorns did most of the work!

Sorry i was talking about fastify

**Comment by Ethan-Arrowood** [comment]
@aspiiire did you figure out a solution here? If you can share a simplified reproduction that'll help us narrow down the problem you're having

**Comment by L2jLiga** [comment]
I've faced with same issue using TypeScript -> ESM
