### ISSUE TITLE
using fastify-passport with passport-jwt strategy

### ISSUE THREAD

**Issue by mkgn** [fastify/fastify-passport#906]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I am using fastify-passport so that I can use many strategies available in passport.js ecosystem. I started to use JWT authentication using [passport-jwt](https://www.passportjs.org/packages/passport-jwt/) and I have a problem wiring things up. Looking at the fastify-passport documentation and passport-jwt documentation in above link has confused me.

So, I have wired up the fastify server as per your documentation

      const fs = require('fs')
      const path = require('path')
      const jwtStrategy = require('passport-jwt').Strategy // installed passport-jwt from npm
      const extractJwt = require('passport-jwt').ExtractJwt; //this is needed according to passport-jwt documentation

then I setup the options for passport-jwt

      var opts = {
        jwtFromRequest : extractJwt.fromAuthHeaderAsBearerToken(),
        secretOrKey : 'secret',
        issuer : 'accounts.examplesoft.com',
        audience : 'yoursite.net',
     }

then register the plugins as mentioned in fastify-passport documentation

      await server.register(fastifySecureSession, { key: fs.readFileSync('./secret-key') })
      await server.register(fastifyPassport.initialize());
      await server.register(fastifyPassport.secureSession())

Then I setup the jwt strategy like below

**[Question - 1]** - Is this call back needed (as per passport-jwt documentation?)
 
      fastifyPassport.use('jwt',new jwtStrategy(opts,function(jwt_payload: any, done: any) {
            console.log("test")
      }))

Finally in my route I have;

[Question - 2] - Is below call back the proper place to validate the jwt and authenticate user against database?

      {
            method: 'POST',
            url: '/users',
            schema: postUserSchema,
            handler: createUser(userRepository),
            preValidation: fastifyPassport.authenticate('jwt', { successRedirect: '/', authInfo: false },  async (request, reply, err, user, info, status) => {
            if (err !== null) {
              console.warn(err)
            } else if (user) {
              console.log(`Hello`)
            }
          }
        )}

There is no error and if I put a break point to the call back in my route, it hits the breakpoint and the [info] object says jwt malformed which is ok because I just send some garbage as bearer data. 

My question is out of the two places (mentioned in Question -1 & Question -2) what is the correct place I should use to do the user authentication/validation.

**Comment by is2ei** [comment]
@mkgn 

> Is this call back needed (as per passport-jwt documentation?)

This question is not for `fastify-passport`. You should ask it in `passport-jwt` community.

> Is below call back the proper place to validate the jwt and authenticate user against database?

The purpose of `callback` option is described in the README.

https://github.com/fastify/fastify-passport#authenticatestrategy-string--strategy--string--strategy-options-authenticateoptions-callback-authenticatecallback

> An optional callback can be supplied to allow the application to override the default manner in which authentication attempts are handled. The callback has the following signature:

**Comment by mkgn** [comment]
Sorry it's difficult to sometimes understand where the question should go to because this plugin is pretty much tight to passport.js. I will try it there. Meanwhile I used fastify/jwt and got the job done until I resolve this.
