### ISSUE TITLE
Invalid Typings for PassportUser in Typescript

### ISSUE THREAD

**Issue by tika** [fastify/fastify-passport#924]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.20.0

### Plugin version

2.3.0

### Node.js version

16.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Ventura 13.4

### Description

In my log in route, I wish to send back to the user their id (therefore I must access the id). I used `request.user` to attempt achieve this (of type PassportUser) but found that PassportUser has no properties (see below)
<img width="920" alt="Screenshot 2023-07-19 at 23 42 36" src="https://github.com/fastify/fastify-passport/assets/48658947/7abbd5e3-0748-4058-b4f3-b6b13c6cdb71">

Hence, when trying to access id (a property of User – what I'm expecting type PassportUser to be & is [if you console log it]) I run into this problem:

<img width="1302" alt="Screenshot 2023-07-19 at 23 38 30" src="https://github.com/fastify/fastify-passport/assets/48658947/b1057268-f080-4ad5-9427-5337350497b2">

### Steps to Reproduce

Relevant `server.ts` code:

```ts

// Sessions
app.register(fastifySecureSession, {
  key: fs.readFileSync(path.join(__dirname, "../example-key")),
});

app.register(fastifyPassport.initialize());
app.register(fastifyPassport.secureSession());

// On login
fastifyPassport.use(
  new passportLocal.Strategy(
    {
      usernameField: "email",
      passwordField: "password",
    },
    // login method
    async (email, password, cb) => {
      const user = await app.prisma.user.findFirst({
        where: {
          email,
        },
      });

      if (!user) {
        return cb("User with this email doesn't exist");
      }

      const isCorrectPassword = await bcrypt.compare(password, user.password);

      if (!isCorrectPassword) {
        return cb("Incorrect password");
      }

      // null and false for all other cases
      return cb(null, user);
    }
  )
);

// register a serializer that stores the user object's id in the session ...
fastifyPassport.registerUserSerializer<User, string>(
  async (user, request) => user.id
);

// ... and then a deserializer that will fetch that user from the database when a request with an id in the session arrives

// TODO: what is unknown??
fastifyPassport.registerUserDeserializer<string, unknown>(
  async (id, request) => {
    return await app.prisma.user.findFirst({
      where: {
        id,
      },
    });
  }
);
```

Relevant route code:

```ts
fastify.post(
    "/",
    {
      preHandler: passport.authenticate("local"),
    },
    async (request, reply) => {
      const user = request.user;

      if (!user) {
        throw new Error(); // Something went wrong...
      }

      stdReply(reply, {
        clientMessage: `Successfully logged in as ${user.id}`,
      });
    }
  );
  ```

### Expected Behavior

I should be able to access the same user object as registered here (of type User).

<img width="798" alt="Screenshot 2023-07-19 at 23 40 39" src="https://github.com/fastify/fastify-passport/assets/48658947/1c55c84e-ecaa-4009-8c32-739e220681d7">

**Comment by tika** [comment]
P.S. If anyone wants to correct my typing for the registerUserDeserializer generic, please do!

```ts
fastifyPassport.registerUserDeserializer<string, unknown>(...);
```

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by cinan** [comment]
downgrading to fastify 4.19 solved typing errors

**Comment by tika** [comment]
> Thanks for reporting!
> 
> Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

Sure! Here's a repo with the relevant code https://github.com/tika/fastify-passport-issue. The issue arises in the `/src/routes/users/login/index.ts` file, where TS complains:

<img width="746" alt="Screenshot 2023-07-21 at 21 57 07" src="https://github.com/fastify/fastify-passport/assets/48658947/2bb2ffd2-bc36-4d9d-8170-837ef51747b1">

**Comment by tika** [comment]
> downgrading to fastify 4.19 solved typing errors

Downgrading did not solve the issue for me

**Comment by tika** [comment]
Update: I don't think it's actually a bug or issue with fastify... someone in 2021 had this problem (on the Discord). Still don't know what I'm doing wrong though.


<img width="556" alt="Screenshot 2023-07-21 at 22 10 08" src="https://github.com/fastify/fastify-passport/assets/48658947/efe06b95-f89a-45e7-92f6-c7c80ae6061b">

**Comment by Uzlopak** [comment]
I think this has to be solved via namespace/type merging.

**Comment by Uzlopak** [comment]
It is already documented:

https://github.com/fastify/fastify-passport#using-with-typescript

**Comment by tika** [comment]
> It is already documented:
> 
> https://github.com/fastify/fastify-passport#using-with-typescript

Thanks, this works (after some tweaking)... I'm sure that I should be using a `.d.ts` file, but when I do that it doesn't seem to actually inject it into the program because the property still doesnt exist. Instead, I have created a separate `global.ts` file, with this code:
```ts
import { User } from "@prisma/client";

declare module "fastify" {
  interface PassportUser extends User {}
}
```
And then imported it in `server.ts` like this:
```ts
import "./global";
```
Is there a better way I could do this?

**Comment by Uzlopak** [comment]
you could use a tripple dash reference

**Comment by tika** [comment]
Like this?

```ts
/// <reference types="@prisma/client" />

declare module "fastify" {
  interface PassportUser extends User {}
}
```

This still overwrites the fastify package...
